### ISSUE TITLE
Enhance Figure 3 /w slider and continuous sampling

### ISSUE THREAD

**Issue by mathieuboudreau** [Notebook-Factory/BayesianRepetoireOverlap#3]
At the suggestion of @dblarremore, we are going create a new & enhanced interactive version of [Figure 3](https://notebook-factory.github.io/BayesianRepetoireOverlap/03Code/Figure3.html) to supplement the Jupyter Book.  I am going to describe what I understood from the meeting that we had last week, so please clarify if I misunderstood anything

* We want a new supplementary interctive figure that will be an enhanced version of Figure 3 from the paper, but won't reproduce it.
  * We should add it in a new Jupyter Book "page" a subsection in the left panel of the Jupyter Book, under the Figure 3 Link (see below)

    <details>

    <img width="285" alt="Capture d’écran 2020-09-03 à 14 21 25" src="https://user-images.githubusercontent.com/1421029/92146932-d03fd680-edf0-11ea-82f7-8e6b954def83.png">

    </details>

* The new figure will have a slider, like [here](https://plotly.com/python/sliders/)
  * The slider will vary the "Number of Samples" parameter (e.g. in the current interactive figure, it's a dropdown between the options of 30, 40, and 50).
  * The slider will continuously vary it (i.e. 30, 31, 32, ..., 49,  50)
  * Instead of doing different samplings for each "Number of Samples" like is currently done,
      <details>
      
      <img width="460" alt="Capture d’écran 2020-09-03 à 14 28 40" src="https://user-images.githubusercontent.com/1421029/92147829-06318a80-edf2-11ea-82fa-7116daae36f3.png">
    
      <img width="396" alt="Capture d’écran 2020-09-03 à 14 31 04" src="https://user-images.githubusercontent.com/1421029/92147997-46910880-edf2-11ea-8ec4-54328383b388.png">

      </details>

      what we'll want to do is simulate it for the total number of points (e.g. 50), and then just plot from 30, 31, ... to 50 for each successive addition of the points.
 
       *  Here is where I'll admit it's not completely clear to me how this can be done, as I've only briefly actually looked a the the code under the hood. I think @zelenkastiot you said you kinda understood how it's likely done, do you want to explain that below? @dblarremore feel free to chime in as well if you can point us in the right direction.

**Comment by mathieuboudreau** [comment]
@zelenkastiot Have you started working on this issue yet? If not, I'm going to start a to-do list below that can get started while we wait to hear back from @dblarremore.

**Comment by mathieuboudreau** [comment]
## To-do

* [x] Create a branch to work on
  * No need to rebuild the Jupyter Book over and over during the development of this branch - we can just develop the feature in the notebook and wait until the end to create the book.
* [x] Create a copy of the [Figure 3 notebook](https://github.com/Notebook-Factory/BayesianRepetoireOverlap/blob/master/content/03Code/Figure3.ipynb) and name it something like `Figure3_enhanced.ipynb`
* [ ] Setup the JupyterBook settings so that it is a subsection below *Figure 3* in the left pannel.
* [x] In the notebook, change the current Plotly figure (without changing code above it yet) so that instead of a drop-down, the three numbers (30, 40, 50) are changed using a [slider](https://plotly.com/python/sliders/)
* [x] Expand his current simulations so that instead of just doing (30, 40, 50), in goes from (30, 31, ..., 49, 50), but still using his old method (all independent "measurements", not a single measurement of 50 but just plotting for the case of 30 points, 21, etc. Ask me for clarification if my explanation here isn't clear
* [ ] **At this point**, if you want to explore and attempt to change the simulation code if you have an idea on how to do it, **make a copy** of the notebook or branch and try it.
* [ ] After the simulation code is correct and has approval from @dblarremore, update Plotly figure to display it if it hasn't been done yet.
* [ ] Make a pull request to master
* [ ] Rebuild the Jupyter Book if it hasn't been done yet.

**Comment by zelenkastiot** [comment]
Hey Mathieu, I started working on the figure but got nowhere because did
not get the idea how the author intended it so I left it like that. I can
check out the stuff you posted earlier

**Comment by mathieuboudreau** [comment]
@zelenkastiot Have you started taking a look at this yet? I had another idea of something we can do while we wait to hear back from Dan. Once you have the notebook created, we could simply expand his current simulations to run from `30, 31, .. 49, 50` and plot that as an intermediate step, but wait to hear back from him to get see how we can do the "single simulation" version of that plot. What do you think? I'll add it to the checklist

**Comment by zelenkastiot** [comment]
Created this repo to run binder more quickly: 

- Repo: https://github.com/zelenkastiot/Figure3_enhanced
- Binder: https://mybinder.org/v2/gh/zelenkastiot/Figure3_enhanced/master?urlpath=lab/tree/Fig3_final.ipynb

The demo figure is working like we discussed @mathieuboudreau, pre-generated only showing the step traces

**Comment by dblarremore** [comment]
The Binder loaded and ran in ~45s for me, and created the interactive plot with clear slider. It works very nicely!

The underlying idea is that the line
`nab = nab_sample(s,na,nb)`
is a sampling process where we take two sets of size `60` which have an intersection of size `s`.  We then subsample the two sets down to sizes `na` and `nb`, respectively, which decreases the size of the intersection from `s` to a randomly generated number `nab`, which is what gets returned. 

In the current code, the number of samples, which is the slider, is equal to `na` and `nb`.  Thus, as you change the slider *currently*, the the function `nab_sample` gets called anew.  [Edit: I was incorrect—I think you precompute for all the slider values, and then just render them anew when the slider gets moved. Sorry!]

The idea would be to instead replace the action of `nab_sample(s,na,nb)` with a function that is no longer parameterized by `na,nb` but instead returns a vector of values for `na=nb=range(30,51)` to match the figure. 

Attached is code that does exactly that. 

Input: `s`
Output: array `nabs` of size 61 such that `nabs[na]` is the number of items shared between the two sets when `na` samples are drawn from each, but now accumulated incrementally.  Note that now, `nabs` will be monotonically increasing in its nonzero values. 

```
def incremental_sample_nab(s,na_min=30,na_max=50):    
    # total repertoire size
    pool = 60
    
    # preallocate the array to be returned
    nabs = np.zeros(pool+1)

    # represent the items in the set by ints from 0 to 60, and from 60-s to 120-s
    # In this way, these sets will share s items
    repertoire_a = np.arange(60)
    repertoire_b = np.arange(60-s,120-s)

    # Create random samples from each repertoire
    sampled_a = np.random.choice(repertoire_a,size=na_min,replace=False)
    sampled_b = np.random.choice(repertoire_b,size=na_min,replace=False)

    # Set Diff to get the items that WEREN'T sampled
    unsampled_a = np.setdiff1d(repertoire_a, sampled_a)
    unsampled_b = np.setdiff1d(repertoire_b, sampled_b)

    # Compute the length of the intersection
    nabs[na_min] = len(np.intersect1d(sampled_a,sampled_b,assume_unique=True))

    # Now shuffle the unsampled items so that choosing the last item
    # from each array is equivalent to drawing from the ordered array at random
    np.random.shuffle(unsampled_a) #inplace shuffle
    np.random.shuffle(unsampled_b) #inplace shuffle

    # Iterate over values of na from 31 up to 50, incrementally gaining one more
    # sample each time.
    for na in np.arange(na_min+1,na_max+1):
        # Sample 1 more from a
        sampled_a = np.append(sampled_a,unsampled_a[-1])
        unsampled_a = np.delete(unsampled_a,-1)

        # Sample 1 more from b
        sampled_b = np.append(sampled_b,unsampled_b[-1])
        unsampled_b = np.delete(unsampled_b,-1)

        # Compute new intersection size
        nabs[na] = len(np.intersect1d(sampled_a,sampled_b,assume_unique=True))

    return nabs
```

**Comment by mathieuboudreau** [comment]
Thanks a lot for the feedback and code @dblarremore ! 

@zelenkastiot is this sufficient for you to complete the figure?

**Comment by zelenkastiot** [comment]
Hey guys, sorry if this reply is running late. Just uploaded the newer version of the notebook: 

- Repo: https://github.com/zelenkastiot/Figure3_enhanced
- Binder: https://mybinder.org/v2/gh/zelenkastiot/Figure3_enhanced/master?urlpath=lab/tree/Fig3_final.ipynb

Changed the code like you said: 

```   Python
# Calculate steps
    nas = [x1, x1+1, x1+2]
    for idxa,na in enumerate(nas):
        nb = na
        for s in np.arange(0,pool+1,1):
            for rep in range(3):
                # Change code to no longer parameterized na,nb 
                nabs = incremental_sample_nab(s)
                # nabs[na] is the number of items shared between the two sets when na samples are drawn from each
                nab = nabs[na]
                planted[idxa,rep,s] = s
                recovered[idxa,rep,s] = e_overlap(na,nb,nab)
                recovered_pts[idxa,rep,s] = 2*nab/(na+nb)
```


Thanks again @dblarremore, hope I understood the modified function correctly!

**Comment by zelenkastiot** [comment]
Let me know if anything is wrong, @mathieuboudreau only thing left is to modify the book structure by 17th. 
I am getting to it right now! 

-- Edit, already done:  #5

**Comment by dblarremore** [comment]
Just opened the notebook with the new incremental formulation. Looks good to me!

**Comment by mathieuboudreau** [comment]
Great - thanks @dblarremore !

@zelenkastiot I think the only thing remaining to do is write up a short paragraph above that figure explaining the difference from the original Figure 3. Once you've done that and pushed it, we can close this issue.
